blank_issues_enabled: true
contact_links:
    - name: zksync-developers Discussion
      url: https://github.com/zkSync-Community-Hub/zkync-developers/discussions
      about: These forms are for zkSync Docs related issues. If you have questions or need help, please visit the zksync-developers Discussion.
