name: "deploy staging 🏗️"
on:
  push:
    branches: [staging]

jobs:
  build_and_deploy:
    env:
      NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
      NUXT_PUBLIC_SITE_URL: ${{ secrets.NUXT_PUBLIC_SITE_URL }}
    if: ${{ github.event.repository.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4
        with:
          ref: "${{ github.event.inputs.ref }}"

      - uses: oven-sh/setup-bun@v1

      - name: "Install dependencies"
        run: bun install
      - name: "Deploy target: staging"
        run: bun run build && bun run generate 

      - uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZKSYNC_DOCS }}"
          target: staging
          projectId: zksync-docs
          channelId: live