name: "deploy staging 🏗️"
on:
  push:
    branches: [staging]
  workflow_dispatch:

env:
  NUXT_SITE_ENV: staging # used for NuxtSEO to disable things like indexing on staging
  HUSKY: 0
  CI: true

concurrency:
  group: staging
  cancel-in-progress: true

jobs:
  build_and_deploy:
    env:
      NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
      ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
      ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
    if: ${{ github.event.repository.full_name == github.repository }}
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          ref: "${{ github.event.inputs.ref }}"

      - uses: oven-sh/setup-bun@v2

      - name: "Install dependencies"
        run: bun install --production --frozen-lockfile
      - name: "Deploy target: staging"
        run: bun run build

      - uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZKSYNC_DOCS_STAGING_5EB09 }}"
          projectId: zksync-docs-staging-5eb09
          channelId: live
